The numpy.random package

Simple Random Data
Simple random sampling is a straight-forward approach to obtaining a random sample. It has many uses in data analytics. In total, there are 10 commands - rand, randn, randint, rand_integers, random_sample, random, ranf, sample, choice, bytes. Each command has a different function. 

Below is a detailed explanation of some of the commands in simple random data.

rand() returns a random set of values of a given shape

In [3]:
import numpy as np
np.random.rand(3) 
#np.random.rand(3) will output random numbers between [0.0,1)
#This means that the numbers range in values starting at 0 up to be not including 1. 

array([0.90895381, 0.05161495, 0.93466177])

Here there are 3 outputs

In [4]:
import numpy as np #Importing the numpy package
np.random.rand(3,2) 

array([[0.59229202, 0.04614585],
       [0.49936179, 0.31653018],
       [0.92979034, 0.38357823]])

If another number was added to the input it will give another dimension to the output. 

In [5]:
import numpy as np #Importing the numpy package
np.random.rand(4,3,2)
#This will give an array of 4x3x2 numbers which are in the range of [0.0,1) 

array([[[0.5830282 , 0.56860906],
        [0.84351253, 0.96153449],
        [0.94398403, 0.2507977 ]],

       [[0.47315046, 0.12785805],
        [0.09928865, 0.75597414],
        [0.26130347, 0.29117888]],

       [[0.39622938, 0.23771821],
        [0.40696074, 0.57275378],
        [0.79835165, 0.12749922]],

       [[0.0407743 , 0.52027993],
        [0.19871085, 0.34601102],
        [0.91921083, 0.04698605]]])

randn() returns a sample(s) from the "standard normal" distribution

In [17]:
import numpy as np #Importing the numpy package
np.random.randn(3) #Generate 3 random numbers

array([ 1.07154215, -1.14986562,  0.40945977])

In [8]:
import numpy as np #Importing the numpy package
np.random.randn(4,3)

array([[ 1.25773463, -0.77185144,  1.92138631],
       [-0.85850267,  0.00388485,  0.09178102],
       [-1.1877637 , -1.46994577, -0.81022596],
       [-0.7090239 ,  0.51341764,  1.65206405]])

np.random.randn outputs an array of 4x3. These are random floats, both positive and negative.

In [10]:
import numpy as np
np.random.randn(3,2)

array([[-1.95381307,  0.3378748 ],
       [-0.58724459, -1.89345493],
       [-1.20908866, -0.95291338]])

randint returns random integer from low (inclusive) to high (exclusive)

In [25]:
import numpy as np #importing the numpy package
np.random.randint(3,15) #randint will ouput a random integer in the range [3,9)

9

In [26]:
import numpy as np #importing the numpy package
np.random.randint(-6,6)

-1

randint(low,high) outputs a single random integer which can include the lowest number but will exclude the higher number. In the two examples shown the range of outputs could be integers [3,15) (including 3, excluding 15) and [-6,6) (including -6 and excluding 6) respectively. 

sample() returns random floats in the half open interval [0.0, 1.0)

In [27]:
import numpy as np #importing the numpy package
np.random.sample(5) #Output a random sample of 5 floats [0.0,1)


array([0.32743581, 0.34713773, 0.66921947, 0.58174294, 0.66366684])

Permutations
There are 2 different commands in this section - shuffle() and permutation()

Below is a detailed explanation of these two commands. 

In [43]:
import numpy as np #import the numpy package
h = np.arange(12) #creating a range
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
np.random.shuffle (h) #Shuffling the range of inputs from 0 (inclusive) to 12 (exclusive)
h

array([ 7,  0,  6,  8,  4, 10,  1, 11,  2,  3,  9,  5])

The 

In [50]:
import numpy as np #import the numpy package
b = np.arange(12) #creating the range
np.random.permutation (b) #output a permuted array range

array([ 2, 10, 11,  5,  1,  0,  6,  8,  7,  4,  9,  3])

Looking at multi dimensional array to show how it is shuffled along

In [52]:
import numpy as np #importing numpy package
c = np.random.rand(4,3,2) # c is a random array of floats 4x3x2 in the range [0.0,1)
c

array([[[0.04659069, 0.30404809],
        [0.48935111, 0.65147437],
        [0.66670752, 0.09688214]],

       [[0.56704137, 0.05909469],
        [0.5264783 , 0.92039292],
        [0.5294789 , 0.87798364]],

       [[0.5282798 , 0.90204742],
        [0.36708682, 0.06394384],
        [0.44223561, 0.51123359]],

       [[0.71648421, 0.58627931],
        [0.27757658, 0.75923366],
        [0.23355609, 0.71954461]]])

In [53]:
np.random.shuffle (c) #shuffles the array of floats
c

array([[[0.56704137, 0.05909469],
        [0.5264783 , 0.92039292],
        [0.5294789 , 0.87798364]],

       [[0.04659069, 0.30404809],
        [0.48935111, 0.65147437],
        [0.66670752, 0.09688214]],

       [[0.5282798 , 0.90204742],
        [0.36708682, 0.06394384],
        [0.44223561, 0.51123359]],

       [[0.71648421, 0.58627931],
        [0.27757658, 0.75923366],
        [0.23355609, 0.71954461]]])

In [54]:
np.random.permutation (c) #output is a permuted array of floats
c

array([[[0.56704137, 0.05909469],
        [0.5264783 , 0.92039292],
        [0.5294789 , 0.87798364]],

       [[0.04659069, 0.30404809],
        [0.48935111, 0.65147437],
        [0.66670752, 0.09688214]],

       [[0.5282798 , 0.90204742],
        [0.36708682, 0.06394384],
        [0.44223561, 0.51123359]],

       [[0.71648421, 0.58627931],
        [0.27757658, 0.75923366],
        [0.23355609, 0.71954461]]])

Distributions
There are over 30 distribution commands

binomial draws samples for a binomial distribution

In [7]:
#Importing packages needed to draw a binomial distribution
import numpy as np #importing numpy package
import pandas as pd #importing pandas package
import matplotlib.pyplot as plt #importing matplotlib package
import scipy.stats as stats
%matplotlib inline
coinflip = stats.binom.rvs(n=10,p=0.5,size=1000) 
print(pd.crosstab(index= "counts", columns= coinflip))
pd.DataFrame(coinflip).hist(range(-0.5,10.5), bins=11)

col_0   0  1   2    3    4    5    6    7   8  9
row_0                                           
counts  1  7  42  106  212  252  215  108  51  6


TypeError: 'float' object cannot be interpreted as an integer