The numpy.random package

In [3]:
import numpy as np
np.random.rand(3) 
#np.random.rand(3) will output random numbers between (0,1] 
#This means that the numbers range in values starting at 0 up to be not including 1. 

array([0.90895381, 0.05161495, 0.93466177])

Here there are 3 outputs

In [4]:
import numpy as np
np.random.rand(3,2)

array([[0.59229202, 0.04614585],
       [0.49936179, 0.31653018],
       [0.92979034, 0.38357823]])

If another number was added to the input it will give another dimension to the output. 

In [5]:
import numpy as np
np.random.rand(4,3,2)

array([[[0.5830282 , 0.56860906],
        [0.84351253, 0.96153449],
        [0.94398403, 0.2507977 ]],

       [[0.47315046, 0.12785805],
        [0.09928865, 0.75597414],
        [0.26130347, 0.29117888]],

       [[0.39622938, 0.23771821],
        [0.40696074, 0.57275378],
        [0.79835165, 0.12749922]],

       [[0.0407743 , 0.52027993],
        [0.19871085, 0.34601102],
        [0.91921083, 0.04698605]]])